### ISSUE TITLE
TIC normalization issue

### ISSUE THREAD

**Issue by mccall-lab-OU** [Functional-Metabolomics-Lab/FBMN-STATS#123]
there may be a glitch in the normalization process in the web app, where it's normalizing by feature rather than by sample (basically in the wrong direction). For example, in the TIC-normalized data, the sum of the peak areas for each feature adds up to 1, rather than the sum of the peak areas for all the features in a given each sample adding to 1. In your data for example, when I sum the TIC-normalized peak areas I get 57.98 for SD_01-2018_10_a, and 52.998 for SD_01-2018_10_b. If I sum the peak areas by features instead, I get a sum of 1 for 92572_151.0351_13.36, 1 for 2513_151.0351_1.13, and so on. I did not manually verify the center-scaling process, so I'm not sure if it's correct.

**Comment by abzer005** [comment]
Thanks so much for looking into this. We checked this and as you mentioned, TIC is doing it feature-centric in the app. But the scaling is totally fine. I checked the notebooks as well and they are working fine. We will fix the TIC issue and release the corrected version soon.

**Comment by abzer005** [comment]
The TIC issue is fixed now. Thanks again for bringing this to our attention
