### ISSUE TITLE
Unable to upload  " Quantification table and meta data files"

### ISSUE THREAD

**Issue by faassenhjr** [Functional-Metabolomics-Lab/FBMN-STATS#124]
![image](https://github.com/Functional-Metabolomics-Lab/FBMN-STATS/assets/12710004/255775ce-82df-4545-86a4-d7a571f151eb)

Was the option deleted to upload your own quantification table and metadata file?

Cheers,
Martijn 

ps. love this tool

**Comment by mccall-lab-OU** [comment]
Same problem here too. Issue is apparent in firefox and chrome.

**Comment by abzer005** [comment]
Hi. The issue has been resolved.
