### ISSUE TITLE
[web app] Quant file upload error

### ISSUE THREAD

**Issue by jyoungheun** [Functional-Metabolomics-Lab/FBMN-STATS#130]
There is an issue when running FBMN-STATS on the web app.
For example, I upload a quant file (.csv) and metadata (.tsv) and conduct several statistics without an issue.
Next, if I upload another set of files, there is no issue when uploading but the newly uploaded file is not used for conducting statistics such as random forest. Instead, the first set of files I uploaded remains on the random forest page.
I tried to shut down the window, delete the cookies, and restart the computer, but the problem remains.
I hope this issue can be solved for the web app users.
Thank you.

**Comment by abzer005** [comment]
Hi. thanks for bringing this up. We will look into this. 👍

**Comment by abzer005** [comment]
Hi. The issue with cache data has been resolved and now a clear cache button is made available :)
