### ISSUE TITLE
suggestion to add remove option for some samples other than blanks?

### ISSUE THREAD

**Issue by marwa38** [Functional-Metabolomics-Lab/FBMN-STATS#133]
Hey :)
This is an awesome tool. 
I am using https://fbmn-statsguide.gnps2.org/
You have a great option to remove the blanks from the dataset as a pre-processing step before running the stats analysis. 
I wonder if you could add another option of removing specific samples that was shown to be outliers later in the FBmnSTATS PCA/PCoA? This will help filter the dataset from outliers. 
![image](https://github.com/user-attachments/assets/9f7312c7-ab39-4a8d-9658-3aaedb9bfe6c)

Please let me know 
Marwa

**Comment by abzer005** [comment]
Hi Marwa, great suggestion to include more filtering options. We’ll definitely add this in the upcoming version, which we plan to release in a few months.
