### ISSUE TITLE
pairwise PERMANOVA? PCoA/PCA by 2 groups?

### ISSUE THREAD

**Issue by marwa38** [Functional-Metabolomics-Lab/FBMN-STATS#134]
Hey 
This is a great tool!!!!

I used https://fbmn-statsguide.gnps2.org/
It is nice that you have (global) PERMANOVA in the workflow. Is it possilble that you could please include pairwise PERMANOVA? as most probably the number of groups in datasets are more than 2. Subeting samples are not available so I can't include/exclude groups as I wish. 
Another point if you don't mind, incase we have many groups under one variable, we need to plot PCA/PCoA for specific 2 groups together where the focus are on. I think it would be quite helpful to inlcude.

Thanks 
Marwa

**Comment by XsirdanielX** [comment]
Thanks a lot Marwa. The web app is meant as a simple educational resource and we might not ab able to implement every feature users desire. For more advanced analysis we recommend to adapt/customize the R or Python notebooks. If you think the implementation would be useful for the broad community, feel free to fork the Repo and make a pull request with you changes. Thank you!
