### ISSUE TITLE
datapoints and boxplots? just a minor suggestion.

### ISSUE THREAD

**Issue by marwa38** [Functional-Metabolomics-Lab/FBMN-STATS#135]
Hi 

You are doing great by making this tool for us, thanks so much. 

I used https://fbmn-statsguide.gnps2.org/
![image](https://github.com/user-attachments/assets/1d924d19-d5ea-4bf8-8506-4c10bf8e2830)
I think that needs abit of improvement in R as the dots/datapoints are to be inside the box plots? as commonly visualised as below:
![image](https://github.com/user-attachments/assets/131e396c-8f0a-45fb-8e98-17eb59c10623)

Thanks 
Marwa

**Comment by XsirdanielX** [comment]
Thanks a lot Marwa. The web app is meant as a simple educational resource and we might not ab able to implement every feature users desire. For more advanced analysis and vizualization needs we recommend to adapt/customize the R or Python notebooks. Thank you!

**Comment by marwa38** [comment]
Thanks for letting me know the main focus of the webtool. It is great tool and was hoping to see more but I agree with you.
